#!/usr/bin/env python3
"""Free IndicTrans2 generator for the remaining Indian languages."""
import json, os, sys, urllib.parse, urllib.request
from datetime import datetime, timezone

import torch
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from IndicTransToolkit import IndicProcessor

TARGETS = {
    "mr": "mar_Deva", "gu": "guj_Gujr", "bn": "ben_Beng",
    "ta": "tam_Taml", "te": "tel_Telu", "kn": "kan_Knda",
    "ml": "mal_Mlym", "pa": "pan_Guru", "or": "ory_Orya",
    "as": "asm_Beng", "ne": "npi_Deva",
}
MODEL = "naklitechie/indictrans2-en-indic-dist-200M"

url = os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_SECRET_KEY") or os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
if not url or not key:
    raise SystemExit("Required env: SUPABASE_URL and SUPABASE_SECRET_KEY")

args = [a for a in sys.argv[1:] if a]
language = next((a for a in args if not a.startswith("--")), "mr")
limit_arg = next((a.split("=",1)[1] for a in args if a.startswith("--limit=")), None)
limit = int(limit_arg) if limit_arg else None
if language not in TARGETS:
    raise SystemExit(f"Unsupported language: {language}. Supported: {', '.join(TARGETS)}")

def api(method, path, payload=None, params=None):
    query = ("?" + urllib.parse.urlencode(params, doseq=True)) if params else ""
    req = urllib.request.Request(
        url.rstrip("/") + "/rest/v1/" + path + query, method=method,
        headers={"apikey": key, "Content-Type": "application/json", "Prefer": "return=representation"},
        data=json.dumps(payload).encode() if payload is not None else None)
    with urllib.request.urlopen(req, timeout=60) as response:
        raw = response.read().decode()
        return json.loads(raw) if raw else []

def main():
    rows = api("GET", "verse_meanings", params={
        "select": "verse_id,meaning,verses(chapter,verse)",
        "language": "eq.en", "version": "eq.v1",
        "review_status": "eq.approved", "limit": "1000"})
    rows.sort(key=lambda r: (r["verses"]["chapter"], r["verses"]["verse"]))
    existing = api("GET", "translations", params={
        "select": "verse_id", "language": f"eq.{language}", "limit": "1000"})
    existing_ids = {r["verse_id"] for r in existing}
    pending = [r for r in rows if r["verse_id"] not in existing_ids]
    if limit:
        pending = pending[:limit]
    if not pending:
        print(f"{language}: nothing to generate")
        return

    print(f"Loading {MODEL} for {language} ({len(pending)} verses)...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL, trust_remote_code=True)
    model = AutoModelForSeq2SeqLM.from_pretrained(MODEL, trust_remote_code=True)
    model.eval()
    processor = IndicProcessor(inference=True)
    target = TARGETS[language]

    for start in range(0, len(pending), 8):
        batch = pending[start:start+8]
        texts = [r["meaning"] for r in batch]
        processed = processor.preprocess_batch(texts, src_lang="eng_Latn", tgt_lang=target)
        inputs = tokenizer(processed, padding="longest", truncation=True, return_tensors="pt")
        with torch.no_grad():
            generated = model.generate(**inputs, max_length=256, num_beams=5, num_return_sequences=1, use_cache=False)
        decoded = tokenizer.batch_decode(generated, skip_special_tokens=True)
        outputs = processor.postprocess_batch(decoded, lang=target)
        for item, meaning in zip(batch, outputs):
            api("POST", "translations", [{
                "verse_id": item["verse_id"], "language": language, "meaning": meaning.strip(),
                "model": "indictrans2-en-indic-dist-200M", "version": "v1-indictrans2",
                "source_language": "en", "review_status": "pending",
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "quality_score": 75,
                "review_note": "Generated by IndicTrans2; human review required."
            }])
        print(f"{language}: {min(start+8, len(pending))}/{len(pending)}")

if __name__ == "__main__":
    main()
